name: gistpay
description: Chat,post,pay- social wallet for niger
publish_to: 'none'
version: 2.0.0+2
environment:
  sdk: '>=3.0.0 <4.0.0'
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  shared_preferences: ^2.2.2
  url_launcher: ^6.2.4
flutter:
  uses-material-design: true
